/**
 * Home of all hand-written implementation for the Payment Gateway Platform.
 *
 * <p>Rule: every piece of business logic we write lives in this package (or a sub-package of it).
 * Classes generated by JHipster (everything else under {@code io.paymentgateway.core}) are never
 * edited. When a generated repository, service, entity or configuration needs more behaviour, it is
 * extended or wrapped here and the extension is what the rest of the code uses.
 *
 * <p>Data-model changes are the one exception to "write it here": they go in the {@code jdl/} files
 * and are regenerated, never hand-patched.
 */
package io.paymentgateway.core.extended;
