# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: paymentgateway
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YWQ4ZTQwODA0NzJjMmE0MzUyYWYzZGFkZTQ1MDQ3ZTczODY4MTlkOWNkZTg3NTQxODVlZTRjNGJjY2VmNTdmN2NhMTU3MDc0YTQxZDNjMTE2NjNkMDViMmZmMTcxMTNlOTRkNzVlNDZmNmQzOTYyOGZiMGFmMDI5N2ExOTAzZmU=
