package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AmlCheckAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmlCheckAllPropertiesEquals(AmlCheck expected, AmlCheck actual) {
        assertAmlCheckAutoGeneratedPropertiesEquals(expected, actual);
        assertAmlCheckAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmlCheckAllUpdatablePropertiesEquals(AmlCheck expected, AmlCheck actual) {
        assertAmlCheckUpdatableFieldsEquals(expected, actual);
        assertAmlCheckUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmlCheckAutoGeneratedPropertiesEquals(AmlCheck expected, AmlCheck actual) {
        assertThat(actual)
            .as("Verify AmlCheck auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmlCheckUpdatableFieldsEquals(AmlCheck expected, AmlCheck actual) {
        assertThat(actual)
            .as("Verify AmlCheck relevant properties")
            .satisfies(a -> assertThat(a.getRiskScore()).as("check riskScore").isEqualTo(expected.getRiskScore()))
            .satisfies(a -> assertThat(a.getDecision()).as("check decision").isEqualTo(expected.getDecision()))
            .satisfies(a -> assertThat(a.getRuleTriggered()).as("check ruleTriggered").isEqualTo(expected.getRuleTriggered()))
            .satisfies(a -> assertThat(a.getCheckedAt()).as("check checkedAt").isEqualTo(expected.getCheckedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAmlCheckUpdatableRelationshipsEquals(AmlCheck expected, AmlCheck actual) {
        assertThat(actual)
            .as("Verify AmlCheck relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getTransaction()).as("check transaction").isEqualTo(expected.getTransaction()));
    }
}
