package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiKeyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyAllPropertiesEquals(ApiKey expected, ApiKey actual) {
        assertApiKeyAutoGeneratedPropertiesEquals(expected, actual);
        assertApiKeyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyAllUpdatablePropertiesEquals(ApiKey expected, ApiKey actual) {
        assertApiKeyUpdatableFieldsEquals(expected, actual);
        assertApiKeyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyAutoGeneratedPropertiesEquals(ApiKey expected, ApiKey actual) {
        assertThat(actual)
            .as("Verify ApiKey auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyUpdatableFieldsEquals(ApiKey expected, ApiKey actual) {
        assertThat(actual)
            .as("Verify ApiKey relevant properties")
            .satisfies(a -> assertThat(a.getKeyPrefix()).as("check keyPrefix").isEqualTo(expected.getKeyPrefix()))
            .satisfies(a -> assertThat(a.getKeyHash()).as("check keyHash").isEqualTo(expected.getKeyHash()))
            .satisfies(a -> assertThat(a.getEnvironment()).as("check environment").isEqualTo(expected.getEnvironment()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getIssuedAt()).as("check issuedAt").isEqualTo(expected.getIssuedAt()))
            .satisfies(a -> assertThat(a.getRevokedAt()).as("check revokedAt").isEqualTo(expected.getRevokedAt()))
            .satisfies(a -> assertThat(a.getGraceExpiresAt()).as("check graceExpiresAt").isEqualTo(expected.getGraceExpiresAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiKeyUpdatableRelationshipsEquals(ApiKey expected, ApiKey actual) {
        assertThat(actual)
            .as("Verify ApiKey relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
