package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AuditLogEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditLogEntryAllPropertiesEquals(AuditLogEntry expected, AuditLogEntry actual) {
        assertAuditLogEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertAuditLogEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditLogEntryAllUpdatablePropertiesEquals(AuditLogEntry expected, AuditLogEntry actual) {
        assertAuditLogEntryUpdatableFieldsEquals(expected, actual);
        assertAuditLogEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditLogEntryAutoGeneratedPropertiesEquals(AuditLogEntry expected, AuditLogEntry actual) {
        assertThat(actual)
            .as("Verify AuditLogEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditLogEntryUpdatableFieldsEquals(AuditLogEntry expected, AuditLogEntry actual) {
        assertThat(actual)
            .as("Verify AuditLogEntry relevant properties")
            .satisfies(a -> assertThat(a.getActorType()).as("check actorType").isEqualTo(expected.getActorType()))
            .satisfies(a -> assertThat(a.getActorId()).as("check actorId").isEqualTo(expected.getActorId()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getEntityType()).as("check entityType").isEqualTo(expected.getEntityType()))
            .satisfies(a -> assertThat(a.getEntityId()).as("check entityId").isEqualTo(expected.getEntityId()))
            .satisfies(a -> assertThat(a.getPreviousHash()).as("check previousHash").isEqualTo(expected.getPreviousHash()))
            .satisfies(a -> assertThat(a.getEntryHash()).as("check entryHash").isEqualTo(expected.getEntryHash()))
            .satisfies(a -> assertThat(a.getRecordedAt()).as("check recordedAt").isEqualTo(expected.getRecordedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuditLogEntryUpdatableRelationshipsEquals(AuditLogEntry expected, AuditLogEntry actual) {
        // empty method
    }
}
