package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CorporateTenantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateTenantAllPropertiesEquals(CorporateTenant expected, CorporateTenant actual) {
        assertCorporateTenantAutoGeneratedPropertiesEquals(expected, actual);
        assertCorporateTenantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateTenantAllUpdatablePropertiesEquals(CorporateTenant expected, CorporateTenant actual) {
        assertCorporateTenantUpdatableFieldsEquals(expected, actual);
        assertCorporateTenantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateTenantAutoGeneratedPropertiesEquals(CorporateTenant expected, CorporateTenant actual) {
        assertThat(actual)
            .as("Verify CorporateTenant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateTenantUpdatableFieldsEquals(CorporateTenant expected, CorporateTenant actual) {
        assertThat(actual)
            .as("Verify CorporateTenant relevant properties")
            .satisfies(a -> assertThat(a.getLegalBusinessName()).as("check legalBusinessName").isEqualTo(expected.getLegalBusinessName()))
            .satisfies(a ->
                assertThat(a.getBusinessRegistrationNumber())
                    .as("check businessRegistrationNumber")
                    .isEqualTo(expected.getBusinessRegistrationNumber())
            )
            .satisfies(a ->
                assertThat(a.getTaxIdentificationNumber())
                    .as("check taxIdentificationNumber")
                    .isEqualTo(expected.getTaxIdentificationNumber())
            )
            .satisfies(a ->
                assertThat(a.getOperatingJurisdiction()).as("check operatingJurisdiction").isEqualTo(expected.getOperatingJurisdiction())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getKycStatus()).as("check kycStatus").isEqualTo(expected.getKycStatus()))
            .satisfies(a -> assertThat(a.getRiskScore()).as("check riskScore").isEqualTo(expected.getRiskScore()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getActivatedAt()).as("check activatedAt").isEqualTo(expected.getActivatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateTenantUpdatableRelationshipsEquals(CorporateTenant expected, CorporateTenant actual) {
        // empty method
    }
}
