package io.paymentgateway.core.domain;

import static io.paymentgateway.core.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CountryPaymentMethodAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryPaymentMethodAllPropertiesEquals(CountryPaymentMethod expected, CountryPaymentMethod actual) {
        assertCountryPaymentMethodAutoGeneratedPropertiesEquals(expected, actual);
        assertCountryPaymentMethodAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryPaymentMethodAllUpdatablePropertiesEquals(CountryPaymentMethod expected, CountryPaymentMethod actual) {
        assertCountryPaymentMethodUpdatableFieldsEquals(expected, actual);
        assertCountryPaymentMethodUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryPaymentMethodAutoGeneratedPropertiesEquals(CountryPaymentMethod expected, CountryPaymentMethod actual) {
        assertThat(actual)
            .as("Verify CountryPaymentMethod auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryPaymentMethodUpdatableFieldsEquals(CountryPaymentMethod expected, CountryPaymentMethod actual) {
        assertThat(actual)
            .as("Verify CountryPaymentMethod relevant properties")
            .satisfies(a ->
                assertThat(a.getMinTxnAmount())
                    .as("check minTxnAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMinTxnAmount())
            )
            .satisfies(a ->
                assertThat(a.getMaxTxnAmount())
                    .as("check maxTxnAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMaxTxnAmount())
            )
            .satisfies(a -> assertThat(a.getSupportsRecurring()).as("check supportsRecurring").isEqualTo(expected.getSupportsRecurring()))
            .satisfies(a ->
                assertThat(a.getSupportsInstantRefund()).as("check supportsInstantRefund").isEqualTo(expected.getSupportsInstantRefund())
            )
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCountryPaymentMethodUpdatableRelationshipsEquals(CountryPaymentMethod expected, CountryPaymentMethod actual) {
        assertThat(actual)
            .as("Verify CountryPaymentMethod relationships")
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getPaymentMethod()).as("check paymentMethod").isEqualTo(expected.getPaymentMethod()));
    }
}
