package io.paymentgateway.core.domain;

import static io.paymentgateway.core.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DisputeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeAllPropertiesEquals(Dispute expected, Dispute actual) {
        assertDisputeAutoGeneratedPropertiesEquals(expected, actual);
        assertDisputeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeAllUpdatablePropertiesEquals(Dispute expected, Dispute actual) {
        assertDisputeUpdatableFieldsEquals(expected, actual);
        assertDisputeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeAutoGeneratedPropertiesEquals(Dispute expected, Dispute actual) {
        assertThat(actual)
            .as("Verify Dispute auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeUpdatableFieldsEquals(Dispute expected, Dispute actual) {
        assertThat(actual)
            .as("Verify Dispute relevant properties")
            .satisfies(a -> assertThat(a.getCaseReference()).as("check caseReference").isEqualTo(expected.getCaseReference()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrencyCode()).as("check currencyCode").isEqualTo(expected.getCurrencyCode()))
            .satisfies(a -> assertThat(a.getReasonCode()).as("check reasonCode").isEqualTo(expected.getReasonCode()))
            .satisfies(a -> assertThat(a.getReasonDescription()).as("check reasonDescription").isEqualTo(expected.getReasonDescription()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getDueDate()).as("check dueDate").isEqualTo(expected.getDueDate()))
            .satisfies(a ->
                assertThat(a.getEvidenceSubmittedAt()).as("check evidenceSubmittedAt").isEqualTo(expected.getEvidenceSubmittedAt())
            )
            .satisfies(a -> assertThat(a.getResolvedAt()).as("check resolvedAt").isEqualTo(expected.getResolvedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeUpdatableRelationshipsEquals(Dispute expected, Dispute actual) {
        assertThat(actual)
            .as("Verify Dispute relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a -> assertThat(a.getTransaction()).as("check transaction").isEqualTo(expected.getTransaction()));
    }
}
