package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisputeEvidenceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeEvidenceAllPropertiesEquals(DisputeEvidence expected, DisputeEvidence actual) {
        assertDisputeEvidenceAutoGeneratedPropertiesEquals(expected, actual);
        assertDisputeEvidenceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeEvidenceAllUpdatablePropertiesEquals(DisputeEvidence expected, DisputeEvidence actual) {
        assertDisputeEvidenceUpdatableFieldsEquals(expected, actual);
        assertDisputeEvidenceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeEvidenceAutoGeneratedPropertiesEquals(DisputeEvidence expected, DisputeEvidence actual) {
        assertThat(actual)
            .as("Verify DisputeEvidence auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeEvidenceUpdatableFieldsEquals(DisputeEvidence expected, DisputeEvidence actual) {
        assertThat(actual)
            .as("Verify DisputeEvidence relevant properties")
            .satisfies(a -> assertThat(a.getEvidenceType()).as("check evidenceType").isEqualTo(expected.getEvidenceType()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getFileUrl()).as("check fileUrl").isEqualTo(expected.getFileUrl()))
            .satisfies(a -> assertThat(a.getFileSizeBytes()).as("check fileSizeBytes").isEqualTo(expected.getFileSizeBytes()))
            .satisfies(a -> assertThat(a.getMimeType()).as("check mimeType").isEqualTo(expected.getMimeType()))
            .satisfies(a -> assertThat(a.getSha256Checksum()).as("check sha256Checksum").isEqualTo(expected.getSha256Checksum()))
            .satisfies(a -> assertThat(a.getUploadedAt()).as("check uploadedAt").isEqualTo(expected.getUploadedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeEvidenceUpdatableRelationshipsEquals(DisputeEvidence expected, DisputeEvidence actual) {
        assertThat(actual)
            .as("Verify DisputeEvidence relationships")
            .satisfies(a -> assertThat(a.getDispute()).as("check dispute").isEqualTo(expected.getDispute()));
    }
}
