package io.paymentgateway.core.domain;

import static io.paymentgateway.core.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ForexRateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertForexRateAllPropertiesEquals(ForexRate expected, ForexRate actual) {
        assertForexRateAutoGeneratedPropertiesEquals(expected, actual);
        assertForexRateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertForexRateAllUpdatablePropertiesEquals(ForexRate expected, ForexRate actual) {
        assertForexRateUpdatableFieldsEquals(expected, actual);
        assertForexRateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertForexRateAutoGeneratedPropertiesEquals(ForexRate expected, ForexRate actual) {
        assertThat(actual)
            .as("Verify ForexRate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertForexRateUpdatableFieldsEquals(ForexRate expected, ForexRate actual) {
        assertThat(actual)
            .as("Verify ForexRate relevant properties")
            .satisfies(a -> assertThat(a.getBaseCurrency()).as("check baseCurrency").isEqualTo(expected.getBaseCurrency()))
            .satisfies(a -> assertThat(a.getQuoteCurrency()).as("check quoteCurrency").isEqualTo(expected.getQuoteCurrency()))
            .satisfies(a -> assertThat(a.getRate()).as("check rate").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRate()))
            .satisfies(a -> assertThat(a.getPlatformSpreadBps()).as("check platformSpreadBps").isEqualTo(expected.getPlatformSpreadBps()))
            .satisfies(a -> assertThat(a.getLockedAt()).as("check lockedAt").isEqualTo(expected.getLockedAt()))
            .satisfies(a -> assertThat(a.getExpiresAt()).as("check expiresAt").isEqualTo(expected.getExpiresAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertForexRateUpdatableRelationshipsEquals(ForexRate expected, ForexRate actual) {
        // empty method
    }
}
