package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JournalEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalEntryAllPropertiesEquals(JournalEntry expected, JournalEntry actual) {
        assertJournalEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertJournalEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalEntryAllUpdatablePropertiesEquals(JournalEntry expected, JournalEntry actual) {
        assertJournalEntryUpdatableFieldsEquals(expected, actual);
        assertJournalEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalEntryAutoGeneratedPropertiesEquals(JournalEntry expected, JournalEntry actual) {
        assertThat(actual)
            .as("Verify JournalEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalEntryUpdatableFieldsEquals(JournalEntry expected, JournalEntry actual) {
        assertThat(actual)
            .as("Verify JournalEntry relevant properties")
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPostedAt()).as("check postedAt").isEqualTo(expected.getPostedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalEntryUpdatableRelationshipsEquals(JournalEntry expected, JournalEntry actual) {
        // empty method
    }
}
