package io.paymentgateway.core.domain;

import static io.paymentgateway.core.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class JournalLineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalLineAllPropertiesEquals(JournalLine expected, JournalLine actual) {
        assertJournalLineAutoGeneratedPropertiesEquals(expected, actual);
        assertJournalLineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalLineAllUpdatablePropertiesEquals(JournalLine expected, JournalLine actual) {
        assertJournalLineUpdatableFieldsEquals(expected, actual);
        assertJournalLineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalLineAutoGeneratedPropertiesEquals(JournalLine expected, JournalLine actual) {
        assertThat(actual)
            .as("Verify JournalLine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalLineUpdatableFieldsEquals(JournalLine expected, JournalLine actual) {
        assertThat(actual)
            .as("Verify JournalLine relevant properties")
            .satisfies(a ->
                assertThat(a.getDebitAmount())
                    .as("check debitAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDebitAmount())
            )
            .satisfies(a ->
                assertThat(a.getCreditAmount())
                    .as("check creditAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCreditAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJournalLineUpdatableRelationshipsEquals(JournalLine expected, JournalLine actual) {
        assertThat(actual)
            .as("Verify JournalLine relationships")
            .satisfies(a -> assertThat(a.getAccount()).as("check account").isEqualTo(expected.getAccount()))
            .satisfies(a -> assertThat(a.getJournalEntry()).as("check journalEntry").isEqualTo(expected.getJournalEntry()));
    }
}
