package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LedgerAccountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerAccountAllPropertiesEquals(LedgerAccount expected, LedgerAccount actual) {
        assertLedgerAccountAutoGeneratedPropertiesEquals(expected, actual);
        assertLedgerAccountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerAccountAllUpdatablePropertiesEquals(LedgerAccount expected, LedgerAccount actual) {
        assertLedgerAccountUpdatableFieldsEquals(expected, actual);
        assertLedgerAccountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerAccountAutoGeneratedPropertiesEquals(LedgerAccount expected, LedgerAccount actual) {
        assertThat(actual)
            .as("Verify LedgerAccount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerAccountUpdatableFieldsEquals(LedgerAccount expected, LedgerAccount actual) {
        assertThat(actual)
            .as("Verify LedgerAccount relevant properties")
            .satisfies(a -> assertThat(a.getAccountCode()).as("check accountCode").isEqualTo(expected.getAccountCode()))
            .satisfies(a -> assertThat(a.getAccountType()).as("check accountType").isEqualTo(expected.getAccountType()))
            .satisfies(a -> assertThat(a.getCurrencyCode()).as("check currencyCode").isEqualTo(expected.getCurrencyCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerAccountUpdatableRelationshipsEquals(LedgerAccount expected, LedgerAccount actual) {
        // empty method
    }
}
