package io.paymentgateway.core.domain;

import static io.paymentgateway.core.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PayoutScheduleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutScheduleAllPropertiesEquals(PayoutSchedule expected, PayoutSchedule actual) {
        assertPayoutScheduleAutoGeneratedPropertiesEquals(expected, actual);
        assertPayoutScheduleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutScheduleAllUpdatablePropertiesEquals(PayoutSchedule expected, PayoutSchedule actual) {
        assertPayoutScheduleUpdatableFieldsEquals(expected, actual);
        assertPayoutScheduleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutScheduleAutoGeneratedPropertiesEquals(PayoutSchedule expected, PayoutSchedule actual) {
        assertThat(actual)
            .as("Verify PayoutSchedule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutScheduleUpdatableFieldsEquals(PayoutSchedule expected, PayoutSchedule actual) {
        assertThat(actual)
            .as("Verify PayoutSchedule relevant properties")
            .satisfies(a -> assertThat(a.getFrequencyMode()).as("check frequencyMode").isEqualTo(expected.getFrequencyMode()))
            .satisfies(a ->
                assertThat(a.getThresholdAmount())
                    .as("check thresholdAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getThresholdAmount())
            )
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPayoutScheduleUpdatableRelationshipsEquals(PayoutSchedule expected, PayoutSchedule actual) {
        assertThat(actual)
            .as("Verify PayoutSchedule relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
