package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RoutingRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoutingRuleAllPropertiesEquals(RoutingRule expected, RoutingRule actual) {
        assertRoutingRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertRoutingRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoutingRuleAllUpdatablePropertiesEquals(RoutingRule expected, RoutingRule actual) {
        assertRoutingRuleUpdatableFieldsEquals(expected, actual);
        assertRoutingRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoutingRuleAutoGeneratedPropertiesEquals(RoutingRule expected, RoutingRule actual) {
        assertThat(actual)
            .as("Verify RoutingRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoutingRuleUpdatableFieldsEquals(RoutingRule expected, RoutingRule actual) {
        assertThat(actual)
            .as("Verify RoutingRule relevant properties")
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getScope()).as("check scope").isEqualTo(expected.getScope()))
            .satisfies(a -> assertThat(a.getCountryCode()).as("check countryCode").isEqualTo(expected.getCountryCode()))
            .satisfies(a -> assertThat(a.getCurrencyCode()).as("check currencyCode").isEqualTo(expected.getCurrencyCode()))
            .satisfies(a -> assertThat(a.getCardBrand()).as("check cardBrand").isEqualTo(expected.getCardBrand()))
            .satisfies(a -> assertThat(a.getPrimaryAdapter()).as("check primaryAdapter").isEqualTo(expected.getPrimaryAdapter()))
            .satisfies(a -> assertThat(a.getFallbackAdapter()).as("check fallbackAdapter").isEqualTo(expected.getFallbackAdapter()))
            .satisfies(a -> assertThat(a.getMaxRetries()).as("check maxRetries").isEqualTo(expected.getMaxRetries()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRoutingRuleUpdatableRelationshipsEquals(RoutingRule expected, RoutingRule actual) {
        assertThat(actual)
            .as("Verify RoutingRule relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
