package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TenantDirectorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDirectorAllPropertiesEquals(TenantDirector expected, TenantDirector actual) {
        assertTenantDirectorAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantDirectorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDirectorAllUpdatablePropertiesEquals(TenantDirector expected, TenantDirector actual) {
        assertTenantDirectorUpdatableFieldsEquals(expected, actual);
        assertTenantDirectorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDirectorAutoGeneratedPropertiesEquals(TenantDirector expected, TenantDirector actual) {
        assertThat(actual)
            .as("Verify TenantDirector auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDirectorUpdatableFieldsEquals(TenantDirector expected, TenantDirector actual) {
        assertThat(actual)
            .as("Verify TenantDirector relevant properties")
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getDateOfBirth()).as("check dateOfBirth").isEqualTo(expected.getDateOfBirth()))
            .satisfies(a -> assertThat(a.getNationality()).as("check nationality").isEqualTo(expected.getNationality()))
            .satisfies(a ->
                assertThat(a.getIdentificationType()).as("check identificationType").isEqualTo(expected.getIdentificationType())
            )
            .satisfies(a ->
                assertThat(a.getIdentificationNumber()).as("check identificationNumber").isEqualTo(expected.getIdentificationNumber())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDirectorUpdatableRelationshipsEquals(TenantDirector expected, TenantDirector actual) {
        assertThat(actual)
            .as("Verify TenantDirector relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
