package io.paymentgateway.core.domain;

import static io.paymentgateway.core.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TenantFeeConfigAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantFeeConfigAllPropertiesEquals(TenantFeeConfig expected, TenantFeeConfig actual) {
        assertTenantFeeConfigAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantFeeConfigAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantFeeConfigAllUpdatablePropertiesEquals(TenantFeeConfig expected, TenantFeeConfig actual) {
        assertTenantFeeConfigUpdatableFieldsEquals(expected, actual);
        assertTenantFeeConfigUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantFeeConfigAutoGeneratedPropertiesEquals(TenantFeeConfig expected, TenantFeeConfig actual) {
        assertThat(actual)
            .as("Verify TenantFeeConfig auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantFeeConfigUpdatableFieldsEquals(TenantFeeConfig expected, TenantFeeConfig actual) {
        assertThat(actual)
            .as("Verify TenantFeeConfig relevant properties")
            .satisfies(a ->
                assertThat(a.getFixedFee()).as("check fixedFee").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFixedFee())
            )
            .satisfies(a ->
                assertThat(a.getPercentageFee())
                    .as("check percentageFee")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPercentageFee())
            )
            .satisfies(a ->
                assertThat(a.getCapAmount()).as("check capAmount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getCapAmount())
            )
            .satisfies(a -> assertThat(a.getFeeBearer()).as("check feeBearer").isEqualTo(expected.getFeeBearer()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantFeeConfigUpdatableRelationshipsEquals(TenantFeeConfig expected, TenantFeeConfig actual) {
        assertThat(actual)
            .as("Verify TenantFeeConfig relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()))
            .satisfies(a ->
                assertThat(a.getCountryPaymentMethod()).as("check countryPaymentMethod").isEqualTo(expected.getCountryPaymentMethod())
            );
    }
}
