package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TenantDomainAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDomainAllPropertiesEquals(TenantDomain expected, TenantDomain actual) {
        assertTenantDomainAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantDomainAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDomainAllUpdatablePropertiesEquals(TenantDomain expected, TenantDomain actual) {
        assertTenantDomainUpdatableFieldsEquals(expected, actual);
        assertTenantDomainUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDomainAutoGeneratedPropertiesEquals(TenantDomain expected, TenantDomain actual) {
        assertThat(actual)
            .as("Verify TenantDomain auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDomainUpdatableFieldsEquals(TenantDomain expected, TenantDomain actual) {
        assertThat(actual)
            .as("Verify TenantDomain relevant properties")
            .satisfies(a -> assertThat(a.getCustomDomain()).as("check customDomain").isEqualTo(expected.getCustomDomain()))
            .satisfies(a -> assertThat(a.getSupportedLocales()).as("check supportedLocales").isEqualTo(expected.getSupportedLocales()))
            .satisfies(a -> assertThat(a.getDefaultLocale()).as("check defaultLocale").isEqualTo(expected.getDefaultLocale()))
            .satisfies(a -> assertThat(a.getFallbackLocale()).as("check fallbackLocale").isEqualTo(expected.getFallbackLocale()))
            .satisfies(a -> assertThat(a.getIsVerified()).as("check isVerified").isEqualTo(expected.getIsVerified()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantDomainUpdatableRelationshipsEquals(TenantDomain expected, TenantDomain actual) {
        assertThat(actual)
            .as("Verify TenantDomain relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
