package io.paymentgateway.core.domain;

import static io.paymentgateway.core.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TenantWalletAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantWalletAllPropertiesEquals(TenantWallet expected, TenantWallet actual) {
        assertTenantWalletAutoGeneratedPropertiesEquals(expected, actual);
        assertTenantWalletAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantWalletAllUpdatablePropertiesEquals(TenantWallet expected, TenantWallet actual) {
        assertTenantWalletUpdatableFieldsEquals(expected, actual);
        assertTenantWalletUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantWalletAutoGeneratedPropertiesEquals(TenantWallet expected, TenantWallet actual) {
        assertThat(actual)
            .as("Verify TenantWallet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantWalletUpdatableFieldsEquals(TenantWallet expected, TenantWallet actual) {
        assertThat(actual)
            .as("Verify TenantWallet relevant properties")
            .satisfies(a -> assertThat(a.getCurrencyCode()).as("check currencyCode").isEqualTo(expected.getCurrencyCode()))
            .satisfies(a ->
                assertThat(a.getAvailableBalance())
                    .as("check availableBalance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAvailableBalance())
            )
            .satisfies(a ->
                assertThat(a.getLockedBalance())
                    .as("check lockedBalance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getLockedBalance())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTenantWalletUpdatableRelationshipsEquals(TenantWallet expected, TenantWallet actual) {
        assertThat(actual)
            .as("Verify TenantWallet relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
