package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WebhookDeliveryAttemptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryAttemptAllPropertiesEquals(WebhookDeliveryAttempt expected, WebhookDeliveryAttempt actual) {
        assertWebhookDeliveryAttemptAutoGeneratedPropertiesEquals(expected, actual);
        assertWebhookDeliveryAttemptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryAttemptAllUpdatablePropertiesEquals(
        WebhookDeliveryAttempt expected,
        WebhookDeliveryAttempt actual
    ) {
        assertWebhookDeliveryAttemptUpdatableFieldsEquals(expected, actual);
        assertWebhookDeliveryAttemptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryAttemptAutoGeneratedPropertiesEquals(
        WebhookDeliveryAttempt expected,
        WebhookDeliveryAttempt actual
    ) {
        assertThat(actual)
            .as("Verify WebhookDeliveryAttempt auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryAttemptUpdatableFieldsEquals(WebhookDeliveryAttempt expected, WebhookDeliveryAttempt actual) {
        assertThat(actual)
            .as("Verify WebhookDeliveryAttempt relevant properties")
            .satisfies(a -> assertThat(a.getEventType()).as("check eventType").isEqualTo(expected.getEventType()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getHttpStatusCode()).as("check httpStatusCode").isEqualTo(expected.getHttpStatusCode()))
            .satisfies(a -> assertThat(a.getAttemptNumber()).as("check attemptNumber").isEqualTo(expected.getAttemptNumber()))
            .satisfies(a -> assertThat(a.getAttemptedAt()).as("check attemptedAt").isEqualTo(expected.getAttemptedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookDeliveryAttemptUpdatableRelationshipsEquals(
        WebhookDeliveryAttempt expected,
        WebhookDeliveryAttempt actual
    ) {
        assertThat(actual)
            .as("Verify WebhookDeliveryAttempt relationships")
            .satisfies(a -> assertThat(a.getSubscription()).as("check subscription").isEqualTo(expected.getSubscription()));
    }
}
