package io.paymentgateway.core.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WebhookSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionAllPropertiesEquals(WebhookSubscription expected, WebhookSubscription actual) {
        assertWebhookSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertWebhookSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionAllUpdatablePropertiesEquals(WebhookSubscription expected, WebhookSubscription actual) {
        assertWebhookSubscriptionUpdatableFieldsEquals(expected, actual);
        assertWebhookSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionAutoGeneratedPropertiesEquals(WebhookSubscription expected, WebhookSubscription actual) {
        assertThat(actual)
            .as("Verify WebhookSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionUpdatableFieldsEquals(WebhookSubscription expected, WebhookSubscription actual) {
        assertThat(actual)
            .as("Verify WebhookSubscription relevant properties")
            .satisfies(a -> assertThat(a.getTargetUrl()).as("check targetUrl").isEqualTo(expected.getTargetUrl()))
            .satisfies(a -> assertThat(a.getSecretHash()).as("check secretHash").isEqualTo(expected.getSecretHash()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWebhookSubscriptionUpdatableRelationshipsEquals(WebhookSubscription expected, WebhookSubscription actual) {
        assertThat(actual)
            .as("Verify WebhookSubscription relationships")
            .satisfies(a -> assertThat(a.getTenant()).as("check tenant").isEqualTo(expected.getTenant()));
    }
}
